[package]
name = "matrix_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
matrix_core = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
uuid = { workspace = true }
