[package]
name = "matrix_physics"
version = "0.1.0"
edition = "2024"

[dependencies]
matrix_core = { workspace = true }
bytemuck = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
