[package]
name = "matrix_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
